# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DragonBall' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DragonBall
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift', '8.3.0-beta'
  pod 'SCLAlertView'
  
end
